services:
  - type: web
    name: project-chimera-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.18
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: OPENAI_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./chimera.db 